### ISSUE TITLE
Cannot automate farming of crops

### ISSUE THREAD

**Issue by jimmed** [wyldmods/KitchenCraft#15]
I've been playing TPPI2 for a while now, and really enjoyed the addition of KitchenCraft. Unfortunately, I cannot seem to automate farming of the KC crops using my normal means (i.e. MineFactory Reloaded Planters/Harvesters, or Steve's Carts 2 farming carts).

I'm not sure which mod would be responsible for compatibility, but I'm posting this here as a starting point :)

**Comment by tterrag1098** [comment]
It'd be great if @skyboy added support in MFR but I might take a look at it at some point. The problem is the special way KC handles crops means it can't use the standard interface (IGrowable) for crops. I wrote a plugin for EnderIO so you can use that to automate it.

**Comment by jimmed** [comment]
Thanks, I'll give that a go and see how it goes :)

**Comment by jimmed** [comment]
I finally got round to trying out KC seeds in an EnderIO Farming Station, but I couldn't place them in its in inventory. Do you have any more info about the aforementioned plugin for EnderIO?

**Comment by jimmed** [comment]
I have, however, discovered that I can do it with OpenComputers robots! Still, any compatibility with something that doesn't require me to write a lot of code would be brilliant.

**Comment by jimmed** [comment]
Just realised I never closed this issue - you can harvest KC crops using [Autonomous Activators](http://ftbwiki.org/Autonomous_Activator) from ExtraUtilities, which are basically automatic right-clickers.
