### ISSUE TITLE
Crash when shift is held over an added food

### ISSUE THREAD

**Issue by abculatter2** [wyldmods/KitchenCraft#16]
http://pastebin.com/WefWJd1V

The first section of that paste is my FoodAdditions.json config, the second section is my crash report.

Whenever I hold shift over the bowlMonsterStew item in the kitchencraft creative menu, the crash happens.

**Comment by tterrag1098** [comment]
It's `potion.confusion` not `potion.nausea`

I should probably verify these on load so the crash is less confusing.

**Comment by tterrag1098** [comment]
I've added that improvement here https://github.com/wyldmods/KitchenCraft/commit/44d47e626ed8298936cf82ef5f1066bbdfb0acd3
