### ISSUE TITLE
Crash when using bonemeal on KitchenCraft Kiwi Seed, grows into Lettuce tree.

### ISSUE THREAD

**Issue by JentheGeek** [wyldmods/KitchenCraft#17]
**Steps to produce error:**
1) Plant a KitchenCraft - Foods Kiwi Seed on the ground

![image](https://cloud.githubusercontent.com/assets/12872858/15672276/4a3fd988-270a-11e6-9c7a-0d267f8b4942.png)

2) Apply bonemeal
Crash: 
[crash-2016-05-31_06.13.40-server.txt](https://github.com/wyldmods/KitchenCraft/files/290905/crash-2016-05-31_06.13.40-server.txt)

(Sorry, I'm at work and they block pastebin)
3) Kiwi Sapling exists

![image](https://cloud.githubusercontent.com/assets/12872858/15672324/99d89aa2-270a-11e6-8fdd-3bf46ccfe1a0.png)

4) Allow sapling to grow - Lettuce Tree!
![image](https://cloud.githubusercontent.com/assets/12872858/15672380/e24bd790-270a-11e6-8589-cc5410e693c7.png)

The non lettuce leaves label as "fruit leaves"

**All versions are in the crash log, but the applicable ones are:**
KitchenCraft - Foods: MC1.7.10-1.0.0-63-Combo
AppleCore: mc1-7-10-1.3.0
EnderCore 1.7.10-0.2.0.31_beta
Forge: 10.13.4.1614
KCauldron: 1.7.10-1614.201 Official

**Applicable sections of the crash log:**
Description: Exception in server tick loop
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IIconRegister
...
at squeek.applecore.asm.Hooks.fireAppleCoreFertilizeEvent(Hooks.java:205)
    at net.minecraft.block.BlockSapling.func_149853_b(BlockSapling.java)
    at net.minecraft.item.ItemDye.applyBonemeal(ItemDye.java:169)

**Comment by tterrag1098** [comment]
This bug only occurs on Cauldron servers and I have never figured out why. Cauldron is unsupported.
